export default function RoadmapVisualizer() {
  return (
    <div className="w-full px-4 sm:px-6 py-16 sm:py-20 md:py-32 min-h-screen flex flex-col justify-center items-center border-b-4 border-black bg-white overflow-hidden">
      <div className="w-full max-w-4xl mx-auto">
        <h2 className="text-3xl sm:text-6xl lg:text-7xl font-black uppercase tracking-tighter text-black mb-12 sm:mb-16 text-center leading-none">Path Extraction</h2>
        <div className="flex flex-col space-y-8 sm:space-y-12 relative before:absolute before:border-l-[3px] sm:before:border-l-4 md:before:border-l-[6px] before:border-black before:h-full before:left-3 sm:before:left-4 md:before:left-1/2 before:-translate-x-1/2 ml-3 sm:ml-4 md:ml-0">
          {[1, 2, 3].map(step => (
            <div key={step} className={`w-[88%] sm:w-[85%] md:w-[45%] p-4 sm:p-6 md:p-8 border-4 border-black bg-white shadow-[4px_4px_0_0_rgba(0,0,0,1)] sm:shadow-[8px_8px_0_0_rgba(0,0,0,1)] md:shadow-[12px_12px_0_0_rgba(0,0,0,1)] md:hover:-translate-y-2 transition-transform self-end ${step % 2 === 0 ? 'md:self-end' : 'md:self-start'}`}>
              <h3 className="text-xl sm:text-2xl md:text-3xl font-black uppercase tracking-tighter text-black leading-none">Phase 0{step}</h3>
              <p className="font-bold text-black uppercase tracking-widest text-xs sm:text-sm mt-3 sm:mt-4 leading-relaxed">Dynamic milestone generated by AI based on your immediate performance weaknesses.</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
