export default function RoadmapVisualizer() {
  return (
    <div className="w-full px-6 py-20 md:py-32 min-h-screen flex flex-col justify-center items-center border-b-[4px] border-black bg-white overflow-hidden">
      <div className="w-full max-w-4xl mx-auto">
        <h2 className="text-4xl sm:text-6xl lg:text-7xl font-black uppercase tracking-tighter text-black mb-16 text-center leading-none">Path Extraction</h2>
        <div className="flex flex-col space-y-12 relative before:absolute before:border-l-[4px] sm:before:border-l-[6px] before:border-black before:h-full before:left-4 sm:before:left-1/2 before:-translate-x-1/2 ml-4 sm:ml-0">
          {[1, 2, 3].map(step => (
            <div key={step} className={`w-[85%] sm:w-[45%] p-6 sm:p-8 border-[4px] border-black bg-white shadow-[8px_8px_0_0_rgba(0,0,0,1)] md:shadow-[12px_12px_0_0_rgba(0,0,0,1)] md:hover:-translate-y-2 transition-transform self-end ${step % 2 === 0 ? 'sm:self-end' : 'sm:self-start'}`}>
              <h3 className="text-2xl sm:text-3xl font-black uppercase tracking-tighter text-black leading-none">Phase 0{step}</h3>
              <p className="font-bold text-black uppercase tracking-widest text-xs sm:text-sm mt-4 leading-relaxed">Dynamic milestone generated by AI based on your immediate performance weaknesses.</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
