import { useState, useEffect } from "react";
import { getDashboardSummary } from "../../services/aiService";

export default function DashboardExecutiveSummary() {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let isMounted = true;
    const fetchSummary = async () => {
      try {
        const data = await getDashboardSummary();
        if (isMounted) {
          setSummary(data.data.summary);
          setLoading(false);
        }
      } catch (err) {
        if (isMounted) {
          setError("Failed to fetch AI summary. Please try again later.");
          setLoading(false);
        }
      }
    };
    fetchSummary();
    return () => { isMounted = false; };
  }, []);

  if (loading) {
    return (
      <div className="w-full border-4 border-black p-6 sm:p-10 bg-gray-50 mb-12 sm:mb-16 shadow-[8px_8px_0_0_rgba(0,0,0,1)] animate-pulse">
        <div className="h-8 bg-gray-300 w-1/3 mb-6"></div>
        <div className="space-y-4">
          <div className="h-4 bg-gray-300 w-full"></div>
          <div className="h-4 bg-gray-300 w-11/12"></div>
          <div className="h-4 bg-gray-300 w-4/5"></div>
        </div>
      </div>
    );
  }

  if (error || !summary) {
    return null;
  }

  // Split paragraphs to render nicely
  const paragraphs = summary.split("\n\n").filter(p => p.trim() !== "");

  return (
    <div className="w-full border-4 border-black p-6 sm:p-10 bg-white mb-12 sm:mb-16 shadow-[12px_12px_0_0_rgba(0,0,0,1)] hover:-translate-y-1 transition-transform duration-300">
      <div className="flex items-center gap-4 mb-6 border-b-4 border-black pb-6">
        <span className="text-4xl">✦</span>
        <div>
          <h2 className="text-2xl sm:text-4xl font-black uppercase tracking-tighter text-black">
            Executive Telemetry Report
          </h2>
          <p className="text-xs font-bold tracking-widest uppercase text-gray-500 mt-1">
            Generated by Gemini AI
          </p>
        </div>
      </div>
      <div className="space-y-6">
        {paragraphs.map((para, idx) => (
          <p key={idx} className="text-base sm:text-lg font-medium leading-relaxed text-black">
            {para}
          </p>
        ))}
      </div>
    </div>
  );
}
